id: AAC0DE08C
title: Guru Yoga of Jetsün Lochen, Queen of Yoginīs
type: translation
pechas:
- I42E4434D
- I6F228638
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:58:01.964330
  last_modified_at: 2023-01-04 12:58:01.964347
  collections:
  - Lochen Chönyi Zangmo
  - Works of Tibetan Masters
alignment_to_base:
  I42E4434D/7BAF: F8A3
  I6F228638/63CC: F8A3
